name: Docker build
on:
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/buildx-pr.yml
      - shell/**
      - .dockerignore
      - alpine.Dockerfile
      - debian.Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Buildx Alpine image
        run: |
          docker buildx build  \
            -f alpine.Dockerfile \
            --progress plain \
            --platform=linux/amd64 \
            .
      - name: Buildx Debian image
        run: |
          docker buildx build  \
            -f debian.Dockerfile \
            --progress plain \
            --platform=linux/amd64 \
            .
