name: Verify
on:
  push:
    paths:
      - .github/workflows/verify.yml
      - shell/**
      - .dockerignore
      - alpine.Dockerfile
      - debian.Dockerfile
  pull_request:
    paths:
      - .github/workflows/verify.yml
      - shell/**
      - .dockerignore
      - alpine.Dockerfile
      - debian.Dockerfile

jobs:
  verify:
    if: github.event.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@v2
      - name: Build Alpine image
        run: docker build -f alpine.Dockerfile .
      - name: Build Debian image
        run: docker build -f debian.Dockerfile .
